server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: 68.183.183.12
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://68.183.183.12:30001/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

logging:
  level:
    org.springframework: INFO
